# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-torchvision-tfms',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-torchvision-tfms',
                'lib_path': 'cjm_torchvision_tfms'},
  'syms': {'cjm_torchvision_tfms.core': {'cjm_torchvision_tfms.core.foo': ('core.html#foo', 'cjm_torchvision_tfms/core.py')}}}
